
macro(read_test_db_dir)
    # Read database of tests.
    file(GLOB test_files LIST_DIRECTORIES FALSE ${TEST_DB}/*.cmake)

    set(TEST_COUNT 0)
    foreach(test_file ${test_files})
        math(EXPR TEST_COUNT "${TEST_COUNT}+1")
        #message(STATUS "test_file: ${test_file}")
        get_filename_component(test_file "${test_file}" NAME)
        add_functional_test(${TEST_DB}/${test_file})
    endforeach()
endmacro()

macro(read_test_db_file)
    set(TEST_COUNT 1)
    add_functional_test(${TEST_DB})
endmacro()

macro(add_functional_test TEST_DESCRIPTION_FILE)
    unset_test_variables()
    include(${TEST_DESCRIPTION_FILE})
    get_filename_component(TEST_NAME "${TEST_DESCRIPTION_FILE}" NAME_WE)
    set(TEST_${TEST_COUNT}_NAME ${TEST_NAME})
    set(TEST_${TEST_COUNT}_URL ${TEST_URL})
    set(TEST_${TEST_COUNT}_BRANCH ${TEST_BRANCH})
    set(TEST_${TEST_COUNT}_TARGETS ${TEST_TARGETS})
    set(TEST_${TEST_COUNT}_TARGETS_ARGS ${TEST_TARGETS_ARGS})
    set(TEST_${TEST_COUNT}_EXPECTED_RESULTS ${TEST_EXPECTED_RESULTS})
    if (DEFINED TEST_TOLERANCE)
        set(TEST_${TEST_COUNT}_TOLERANCE ${TEST_TOLERANCE})
    else ()
        set(TEST_${TEST_COUNT}_TOLERANCE 1e-14)
    endif ()
endmacro()

macro(unset_test_variables)
    unset(TEST_NAME)
    unset(TEST_URL)
    unset(TEST_BRANCH)
    unset(TEST_TARGETS)
    unset(TEST_TARGETS_ARGS)
    unset(TEST_EXPECTED_RESULTS)
    unset(TEST_TOLERANCE)

    unset(PYTEST_SCRIPTS)
    unset(PYTEST_SCRIPTS_ARGS)
    unset(PYTEST_EXPECTED_RESULTS)

    unset(TEST_MULTI_PROCESS)
    unset(TEST_NP)
    #unset(TEST_NAME)
endmacro()