
macro(write_target_test TEST_NAME TEST_TARGET TEST_ROOT TEST_EXPECTED_RESULTS TEST_TOLERANCE _OUTPUT)

    set(_TMP_OUTPUT "

# Create output directory
file(MAKE_DIRECTORY \${CMAKE_BINARY_DIR}/test_runs/${TEST_NAME})

add_test(NAME test_${TEST_NAME}
   COMMAND ${CMAKE_COMMAND}
   -DTEST_NAME=${TEST_NAME}
   -DNDIFF_EXECUTABLE=${NDIFF_EXECUTABLE}
   -DTEST_CMD=\$<TARGET_FILE:${TEST_TARGET}>
   -DTEST_TOLERANCE=${TEST_TOLERANCE}
   -DEXPECTED_OUTPUT=${TEST_ROOT}/${TEST_EXPECTED_RESULTS}
   -DTEST_OUTPUT=\${CMAKE_BINARY_DIR}/test_runs/${TEST_NAME}
   -P ${TESTS_BASE_DIR}/run_test.cmake)
")

    set(${_OUTPUT} ${_TMP_OUTPUT})
endmacro()
